# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
#
# NOTE:  As of 13 MAY 2022, require Python >= 3.8 in order for h5py and numpy dependencies to work.  ReadTheDocs uses Python 3.7 by default, and for some reason pip is not correctly installing compatible dependency versions.
build:
  os: ubuntu-20.04  # Must set before setting tools.python
  tools:
    python: "3"     # Use latest stable CPython version

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
